// <auto-generated />
using System;
using Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260223032642_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Flight.Models.City", b =>
                {
                    b.Property<string>("CityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = "CHI",
                            Name = "Chicago"
                        },
                        new
                        {
                            CityId = "NYC",
                            Name = "New York"
                        },
                        new
                        {
                            CityId = "DXB",
                            Name = "Dubai"
                        },
                        new
                        {
                            CityId = "LON",
                            Name = "London"
                        },
                        new
                        {
                            CityId = "HKG",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            CityId = "SFO",
                            Name = "San Francisco"
                        });
                });

            modelBuilder.Entity("Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("FromCityId");

                    b.HasIndex("ToCityId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "UA3321",
                            FromCityId = "CHI",
                            Price = 235m,
                            ToCityId = "NYC"
                        },
                        new
                        {
                            FlightId = 2,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "QA1078",
                            FromCityId = "DXB",
                            Price = 590m,
                            ToCityId = "LON"
                        },
                        new
                        {
                            FlightId = 3,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FlightNumber = "CA9087",
                            FromCityId = "HKG",
                            Price = 900m,
                            ToCityId = "SFO"
                        });
                });

            modelBuilder.Entity("Flight.Models.Flight", b =>
                {
                    b.HasOne("Flight.Models.City", "FromCity")
                        .WithMany()
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Flight.Models.City", "ToCity")
                        .WithMany()
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });
#pragma warning restore 612, 618
        }
    }
}
